FUNCTION Z_FM_PARAMS_RTTS_TEST.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(C) TYPE  C
*"     REFERENCE(N) TYPE  N
*"     REFERENCE(P) TYPE  P
*"     REFERENCE(X) TYPE  X
*"     REFERENCE(DECFLOAT) TYPE  DECFLOAT
*"     REFERENCE(NUMERIC) TYPE  NUMERIC
*"     REFERENCE(SIMPLE) TYPE  SIMPLE
*"     REFERENCE(CLIKE) TYPE  CLIKE
*"     REFERENCE(CSEQUENCE) TYPE  CSEQUENCE
*"     REFERENCE(XSEQUENCE) TYPE  XSEQUENCE
*"     REFERENCE(TABLE) TYPE  TABLE
*"     REFERENCE(ANY_TABLE) TYPE  ANY TABLE
*"     REFERENCE(STANDARD_TABLE) TYPE  STANDARD TABLE
*"     REFERENCE(SORTED_TABLE) TYPE  SORTED TABLE
*"     REFERENCE(INDEX_TABLE) TYPE  INDEX TABLE
*"     REFERENCE(HASHED_TABLE) TYPE  HASHED TABLE
*"     REFERENCE(ANY) TYPE  ANY
*"     REFERENCE(DATA) TYPE  DATA
*"     REFERENCE(INT1) TYPE  INT1
*"     REFERENCE(INT2) TYPE  INT2
*"     REFERENCE(INT4) TYPE  INT4
*"     REFERENCE(INT8) TYPE  INT8
*"     REFERENCE(BIG_C) TYPE  ZIF_FM_PARAMS_RTTS_TEST=>TY_BIG_C
*"     REFERENCE(BIG_N) TYPE  ZIF_FM_PARAMS_RTTS_TEST=>TY_BIG_N
*"     REFERENCE(BIG_P) TYPE  ZIF_FM_PARAMS_RTTS_TEST=>TY_BIG_P
*"     REFERENCE(BIG_X) TYPE  ZIF_FM_PARAMS_RTTS_TEST=>TY_BIG_X
*"     REFERENCE(DECFLOAT16) TYPE  DECFLOAT16
*"     REFERENCE(DECFLOAT34) TYPE  DECFLOAT34
*"     REFERENCE(F) TYPE  F
*"     REFERENCE(D) TYPE  D
*"     REFERENCE(T) TYPE  T
*"     REFERENCE(STRING) TYPE  STRING
*"     REFERENCE(XSTRING) TYPE  XSTRING
*"     REFERENCE(BAPIRET2) TYPE  BAPIRET2
*"     REFERENCE(REF_DATA) TYPE REF TO  DATA
*"     REFERENCE(REF_I) TYPE REF TO  I
*"     REFERENCE(REF_OBJECT) TYPE REF TO  OBJECT
*"  TABLES
*"      STANDARD_TABLE_COMPLETE TYPE  STRING_TABLE
*"      STANDARD_TABLE_COMPLETE2 STRUCTURE  BAPIRET2
*"----------------------------------------------------------------------
*    structure_ TYPE zif_fm_params_rtts_test=>ty_structure.








ENDFUNCTION.
