CLASS zcx_fm_params_rtts DEFINITION
  INHERITING FROM cx_static_check
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_fm_params_rtts IMPLEMENTATION.
ENDCLASS.
